### ISSUE TITLE
conflicts when multiple rxjs versions installed

### ISSUE THREAD

**Issue by mathieudutour** [ar90n/serverless-s3-local#30]
Those 2 lines: https://github.com/ar90n/serverless-s3-local/blob/master/index.js#L10-L11 breaks when another package installs the version 6 of rxjs. Since `serverless-s3-local` doesn't explicitly declare a dependency on `rxjs@5`, `rxjs@6` might be loaded and `rxjs/add/operator/map` doesn't work on this version if `rxjs-compat` is not a dependency as well.

Removing those 2 lines seems to work but I'm not sure what are the side effects so I'll let you find a proper fix ;)

Logs:
```
Error: Cannot find module 'rxjs-compat/add/operator/map'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (xxxxx/node_modules/rxjs/add/operator/map.js:3:1)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (xxxxx/node_modules/serverless-s3-local/index.js:10:1)
```

**Comment by ar90n** [comment]
Hi @mathieudutour 
Thanks for your report.
This is a bug which is caused by my misunderstanding of javascript.
I removed them and published new version.
Please use it vie npm.

**Comment by mathieudutour** [comment]
Cool thanks!
