### ISSUE TITLE
AWS is not defined

### ISSUE THREAD

**Issue by peebles** [ar90n/serverless-s3-local#581]
In version 0.6.22, I am getting:

ReferenceError: AWS is not defined
    at ServerlessS3Local.getClient (/Users/peebles/cortina/ca-portal/node_modules/serverless-s3-local/index.js:353:21)
    at ServerlessS3Local.createBuckets (/Users/peebles/cortina/ca-portal/node_modules/serverless-s3-local/index.js:325:27)
    ...

And indeed, in index.js line 353 there is a reference to AWS that was never defined:

```js
  getClient() {
    const { S3 } = require("@aws-sdk/client-s3");
    return new S3({
      s3ForcePathStyle: true,
      endpoint: new AWS.Endpoint(
        `http://${this.options.host}:${this.options.port}`
      ),
      accessKeyId: this.options.accessKeyId,
      secretAccessKey: this.options.secretAccessKey,
    });
  }
```

Or am I missing something here?

**Comment by filipemacedo** [comment]
Where do you import AWS?

See an example:

```
import { S3, Endpoint } from "aws-sdk";
```
