### ISSUE TITLE
TypeError: Cannot read property 'timeout' of undefined when used with  serverless-offline version 4.10.0 plugin

### ISSUE THREAD

**Issue by david-dacostad** [ar90n/serverless-s3-local#63]
With **serverless-offline@4.10.0** we are getting the following error:

```
TypeError: Cannot read property 'timeout' of undefined
    at createLambdaContext (/Users/david.dacosta/repositories/private-repos/pipelines/node_modules/serverless-offline/src/createLambdaContext.js:10:44)
    at Object.keys.forEach.key (/Users/david.dacosta/repositories/private-repos/pipelines/node_modules/serverless-s3-local/index.js:318:29)
    at Array.forEach (<anonymous>)
    at ServerlessS3Local.getEventHandlers (/Users/david.dacosta/repositories/private-repos/pipelines/node_modules/serverless-s3-local/index.js:315:41)
    at ServerlessS3Local.subscribe (/Users/david.dacosta/repositories/private-repos/pipelines/node_modules/serverless-s3-local/index.js:137:31)
    at Promise (/Users/david.dacosta/repositories/private-repos/pipelines/node_modules/serverless-s3-local/index.js:214:12)
    at new Promise (<anonymous>)
    at ServerlessS3Local.startHandler (/Users/david.dacosta/repositories/private-repos/pipelines/node_modules/serverless-s3-local/index.js:178:12)
    at BbPromise.reduce (/Users/david.dacosta/repositories/private-repos/pipelines/node_modules/serverless/lib/classes/PluginManager.js:408:55)
    at tryCatcher (/Users/david.dacosta/repositories/private-repos/pipelines/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/Users/david.dacosta/repositories/private-repos/pipelines/node_modules/bluebird/js/release/reduce.js:157:18)
    at Object.gotAccum (/Users/david.dacosta/repositories/private-repos/pipelines/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/Users/david.dacosta/repositories/private-repos/pipelines/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/david.dacosta/repositories/private-repos/pipelines/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/david.dacosta/repositories/private-repos/pipelines/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/david.dacosta/repositories/private-repos/pipelines/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/david.dacosta/repositories/private-repos/pipelines/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Users/david.dacosta/repositories/private-repos/pipelines/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/david.dacosta/repositories/private-repos/pipelines/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/david.dacosta/repositories/private-repos/pipelines/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/david.dacosta/repositories/private-repos/pipelines/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
```
Line 138 on index.js should be changed to 
`const lambdaContext = createLambdaContext(serviceFunction, this.service.provider);`

This will satisfy the issue with signature of createLambdaContext provided by **serverless-offline** plugin

**Comment by dherault** [comment]
Hi guys, I wanted to report the same issue, but it's already done with a correct fix :) cheers!

**Comment by ar90n** [comment]
@david-dacostad 
Thanks for your report and advice. I fixed this issue by following your advice. Please use the latest version v0.4.4 via npm !!

@dherault 
Thank for your comment.  serverless-offline is quite useful for me. Thanks again.
