### ISSUE TITLE
Usage fails with or without AWS Credentials

### ISSUE THREAD

**Issue by sudosoul** [ar90n/serverless-s3-local#65]
I am unable to use this. If I start `sls offline` without my AWS keys exported, I get this error:

```
(node:70507) UnhandledPromiseRejectionWarning: CredentialsError: Missing credentials in config
    at ClientRequest.<anonymous> (/my/path/node_modules/aws-sdk/lib/http/node.js:83:34)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at ClientRequest.emit (events.js:208:7)
    at Socket.emitTimeout (_http_client.js:718:34)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:422:8)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
```

But even when I do export my valid AWS credentials, I get this error:
```
info: PUT /local-bucket/35e6ab220ef8eafb5ae749f77a3924fb 403 10ms -
{ InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
    at Request.extractError (/my/path/node_modules/aws-sdk/lib/services/s3.js:585:35)
    at Request.callListeners (/my/path/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/my/path/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/my/path/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/my/path/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/my/path/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /my/path/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/my/path/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/my/path/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/my/path/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/my/path/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/my/path/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/my/path/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/my/path/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /my/path/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/my/path/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/my/path/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/my/path/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/my/path/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/my/path/node_modules/aws-sdk/lib/event_listeners.js:299:13)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
  message: 'The AWS Access Key Id you provided does not exist in our records.',
  code: 'InvalidAccessKeyId',
  region: null,
  time: 2019-05-16T20:45:16.542Z,
  requestId: null,
  extendedRequestId: undefined,
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 44.172674758005705 }
```

My S3 initialization code block looks like
```
// Initialize S3
const {AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION} = Config.get('AWS')
const s3Config = {
  accessKeyId: AWS_ACCESS_KEY_ID,
  secretAccessKey: AWS_SECRET_ACCESS_KEY,
  region: AWS_REGION
}
if (Config.get('NODE_ENV') === 'debug') {
  // Use local S3 for local development
  s3Config.s3ForcePathStyle = true
  s3Config.endpoint = new AWS.Endpoint('http://localhost:4002')
}
const s3 = new AWS.S3(s3Config)
```

**Comment by ar90n** [comment]
Hi @sudosoul 
Thanks for your report. I guess that your accessKeyId and secretAccessKey are wrong. Please assign ‘S3RVER’ to accessKeyId and secretAccessKey like serverless-s3-local examples.

**Comment by codetelo** [comment]
I'm actually experiencing the same problem following the simple event example and in my S3 initialization it looks like:
` const S3 = new AWS.S3({
    s3ForcePathStyle: true,
    endpoint: new AWS.Endpoint('http://localhost:4569'),
    accessKeyId: 'S3RVER',
    secretAccessKey: 'S3RVER',
  });`

**Comment by ar90n** [comment]
Hi @codetelo 
Thanks for your comment. Please tell me about your situation in more detail. I guess you run the following commands. Is it correct ?

Server:
```
$ cd path/to/simple_event_example
$ npm install
$ sls offline start
```

Client:
```
$ curl http://localhost:3000
```

**Comment by sudosoul** [comment]
@ar90n @codetelo 

Thanks I was able to get this working by doing the following

1. Setting the following S3 config options
```
const s3Config = {
  accessKeyId: 'S3RVER',
  secretAccessKey: 'S3RVER',
  region: 'us-east-2' (can use any region),
  s3ForcePathStyle: true,
  endpoint = new AWS.Endpoint('http://localhost:4002')
}
const s3 = new AWS.S3(s3Config)
```

2. Setting the following my serverless.yml
```
custom:
  s3:
    host: 0.0.0.0
    port: 4002
    directory: /tmp/serverless-s3-offline
```

3. I had to manually create the directory for the local s3 bucket
```
mkdir -p /tmp/serverless-s3-offline/{name-of-bucket-i-want-to-use}
# Example: mkdir -p /tmp/serverless-s3-offline/local-bucket
```

4. Finally, I make sure that my app code has the Bucket value set to `local-bucket` (or whatever I have named the bucket in the step above. 

@ar90n you able to perhaps update the README with these steps?
If not, I can open a PR when I have a free chance this week if you like.

**Comment by ar90n** [comment]
Hi @sudosoul 
It sounds great! But I still have a doubt. In my environment, the directory for the S3 buckets is created automatically as following.

```
$ cat serverless.yml
service: serverless-s3-local-example
provider:
  name: aws
  runtime: nodejs8.10
plugins:
  - serverless-s3-local
  - serverless-plugin-existing-s3
  - serverless-offline
custom:
  s3:
    host: 0.0.0.0
    port: 4002
    directory: /tmp//serverless-s3-offline
resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: local-bucket
functions:
  webhook:
    handler: handler.webhook
    events:
      - http:
          method: get
$ ls /tmp//serverless-s3-offline
ls: cannot access '/tmp//serverless-s3-offline': No such file or directory
$ sls offline start &
[1] 2997
starting handler
S3 local started ( port:4002 )
Serverless: creating bucket: local-bucket
error: Error creating bucket. Bucket "local-bucket" already exists
info: PUT /local-bucket 409 18ms -
Serverless: Starting Offline: undefined/undefined.

Serverless: Routes for webhook:
Serverless: GET /

Serverless: Offline listening on http://localhost:3000

$ ls /tmp//serverless-s3-offline
local-bucket
```

**Comment by sudosoul** [comment]
@ar90n 
My assumption is that it's getting created because of you have defined the S3 bucket as a resource maybe?
```
resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: local-bucket
```

In my case, I don't want serverless framework to create a S3 bucket for me - I want it to use an existing one. So, I don't use that `NewResource` block in my serverless.yml. I feel like this could be a popular use case (for example, I minimize the amount of infrastructure serverless framework creates & manages, and instead create & manage these infrastructure resources myself via my own preferred IaC tool - Terraform. 

Can you try removing it, and letting me know if the bucket still gets created in your `/tmp` directory.

**Comment by ar90n** [comment]
Hi @sudosoul 
Thanks for your reply. I reproduced your situation when I removed the configurations about S3 Bucket from resources section. And I have understood your use-case such as using IaC tools. It is very useful information for me. I’ll  improve README by adding these steps.

**Comment by gndelia** [comment]
I'm having the same issue here (using AWS V3)

My config initialization is

```js
const s3Client = new S3Client({
  region: 'us-east-2',
  accessKeyId: 'S3RVER',
  secretAccessKey: 'S3RVER',
  forcePathStyle: true,
  endpoint: 'http://localhost:4569'
})
```

and I get 

> InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.

if I remove the `endpoint` property, I get

> PermanentRedirect: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.

**Comment by ar90n** [comment]
@gndelia 
Thanks for your comment. And I'm sorry for the trouble.
Please try the following codes.

```js
const s3Client = new S3Client({
  region: 'us-east-2',
  credentials: {
    accessKeyId: 'S3RVER',
    secretAccessKey: 'S3RVER',
  },
  forcePathStyle: true,
  endpoint: 'http://localhost:4569'
})
```

Now I'm trying to upgrade the dependency of serverless-s3-local from AWS SDK v2 to AWS SDK v3.
And it seems that it works correctly in my local environment. So it will be released in these days.

**Comment by 1000ship** [comment]
@ar90n Thx! it works
