### ISSUE TITLE
Entire serverless-offline crashed if s3 event handlers throw

### ISSUE THREAD

**Issue by gevorggalstyan** [ar90n/serverless-s3-local#73]
If I throw in any of functions that have s3 as events the entire local serverless instance exits.

For example, a simple line like this will crash the app:

```js
throw new Error("Something went wrong");
```

and the response in the terminal looks something like this:

```txt
Error --------------------------------------------------
 
  Error: Something went wrong
    at ./src/functions/event-listeners/listener.ts.exports.ts (/Users/g/Sites/app/.webpack/service/src/functions/event-listeners/webpack:/src/functions/event-listeners/listener.ts:352:9)
    at Object.func (/Users/g/Sites/app/node_modules/serverless-s3-local/index.js:385:11)
    at /Users/g/Sites/app/node_modules/serverless-s3-local/index.js:172:43
    at SafeSubscriber.s3eventSubscription.s3Event.pipe.subscribe.handler [as _next] (/Users/g/Sites/app/node_modules/serverless-s3-local/index.js:177:9)
    at SafeSubscriber.__tryOrUnsub (/Users/g/Sites/app/node_modules/rxjs/src/internal/Subscriber.ts:265:10)
    at SafeSubscriber.next (/Users/g/Sites/app/node_modules/rxjs/src/internal/Subscriber.ts:207:14)
    at Subscriber._next (/Users/g/Sites/app/node_modules/rxjs/src/internal/Subscriber.ts:139:22)
    at Subscriber.next (/Users/g/Sites/app/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at MergeMapSubscriber.notifyNext (/Users/g/Sites/app/node_modules/rxjs/src/internal/operators/mergeMap.ts:162:22)
    at InnerSubscriber._next (/Users/g/Sites/app/node_modules/rxjs/src/internal/InnerSubscriber.ts:17:17)
    at InnerSubscriber.Subscriber.next (/Users/g/Sites/app/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at /Users/g/Sites/app/node_modules/rxjs/src/internal/util/subscribeToArray.ts:9:16
    at Object.subscribeToResult (/Users/g/Sites/app/node_modules/rxjs/src/internal/util/subscribeToResult.ts:28:29)
    at MergeMapSubscriber._innerSub (/Users/g/Sites/app/node_modules/rxjs/src/internal/operators/mergeMap.ts:148:5)
    at MergeMapSubscriber._tryNext (/Users/g/Sites/app/node_modules/rxjs/src/internal/operators/mergeMap.ts:141:10)
    at MergeMapSubscriber._next (/Users/g/Sites/app/node_modules/rxjs/src/internal/operators/mergeMap.ts:125:12)
    at MergeMapSubscriber.Subscriber.next (/Users/g/Sites/app/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at MapSubscriber._next (/Users/g/Sites/app/node_modules/rxjs/src/internal/operators/map.ts:89:22)
    at MapSubscriber.Subscriber.next (/Users/g/Sites/app/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at S3rver.handler (/Users/g/Sites/app/node_modules/rxjs/src/internal/observable/fromEvent.ts:201:20)
    at S3rver.emit (events.js:198:13)
    at S3rver.EventEmitter.emit (domain.js:448:20)
    at triggerS3Event (/Users/g/Sites/app/node_modules/s3rver/lib/controllers/object.js:35:11)
    at Object.putObject (/Users/g/Sites/app/node_modules/s3rver/lib/controllers/object.js:280:5)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              10.16.0
     Framework Version:         1.50.0
     Plugin Version:            1.3.8
     SDK Version:               2.1.0
 
Waiting for the debugger to disconnect...
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serverless-api@1.0.0 start: `NODE_OPTIONS='--max-old-space-size=8192' node --inspect ./node_modules/.bin/serverless offline start -s local --location .webpack/service`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serverless-api@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/g/.npm/_logs/2019-08-21T22_06_46_492Z-debug.log
```

**Comment by ar90n** [comment]
@gevorggalstyan 
Thanks for your comment. I tried to reproduce your situation, but a I couldn’t.  The output in my environment is as following.

```
info: Stored object "locale.json" in bucket "local-bucket" successfully                                                
Error while running handler Error: Something went wrong                                              
    at module.exports.s3hook (/home/argon/workspace/serverless-s3-local/example/simple_event/handler.js:19:9)      
    at Object.func (/home/argon/workspace/serverless-s3-local/index.js:387:11)                       
    at /home/argon/workspace/serverless-s3-local/index.js:171:45                       
    at SafeSubscriber._next (/home/argon/workspace/serverless-s3-local/index.js:176:9)         
    at SafeSubscriber.__tryOrUnsub (/home/argon/workspace/serverless-s3-local/node_modules/rxjs/src/internal/Subscriber.ts:270:10)
    at SafeSubscriber.next (/home/argon/workspace/serverless-s3-local/node_modules/rxjs/src/internal/Subscriber.ts:212:14)
    at Subscriber._next (/home/argon/workspace/serverless-s3-local/node_modules/rxjs/src/internal/Subscriber.ts:141:22)
    at Subscriber.next (/home/argon/workspace/serverless-s3-local/node_modules/rxjs/src/internal/Subscriber.ts:101:12)
    at MergeMapSubscriber.notifyNext (/home/argon/workspace/serverless-s3-local/node_modules/rxjs/src/internal/operators/mergeMap.ts:159:22)
    at InnerSubscriber._next (/home/argon/workspace/serverless-s3-local/node_modules/rxjs/src/internal/InnerSubscriber.ts:17:17)
    at InnerSubscriber.Subscriber.next (/home/argon/workspace/serverless-s3-local/node_modules/rxjs/src/internal/Subscriber.ts:101:12)
    at /home/argon/workspace/serverless-s3-local/node_modules/rxjs/src/internal/util/subscribeToArray.ts:9:16                     
    at Object.subscribeToResult (/home/argon/workspace/serverless-s3-local/node_modules/rxjs/src/internal/util/subscribeToResult.ts:25:29)
    at MergeMapSubscriber._innerSub (/home/argon/workspace/serverless-s3-local/node_modules/rxjs/src/internal/operators/mergeMap.ts:145:5)
    at MergeMapSubscriber._tryNext (/home/argon/workspace/serverless-s3-local/node_modules/rxjs/src/internal/operators/mergeMap.ts:138:10)
    at MergeMapSubscriber._next (/home/argon/workspace/serverless-s3-local/node_modules/rxjs/src/internal/operators/mergeMap.ts:122:12)     
    at MergeMapSubscriber.Subscriber.next (/home/argon/workspace/serverless-s3-local/node_modules/rxjs/src/internal/Subscriber.ts:101:12)
    at MapSubscriber._next (/home/argon/workspace/serverless-s3-local/node_modules/rxjs/src/internal/operators/map.ts:86:22)          
    at MapSubscriber.Subscriber.next (/home/argon/workspace/serverless-s3-local/node_modules/rxjs/src/internal/Subscriber.ts:101:12)
    at S3rver.handler (/home/argon/workspace/serverless-s3-local/node_modules/rxjs/src/internal/observable/fromEvent.ts:197:20)           
    at S3rver.emit (events.js:203:13)                                                                                                     
    at S3rver.EventEmitter.emit (domain.js:471:20)                                                                                        
    at triggerS3Event (/home/argon/workspace/serverless-s3-local/node_modules/s3rver/lib/controllers/object.js:30:11)                  
    at Object.putObject (/home/argon/workspace/serverless-s3-local/node_modules/s3rver/lib/controllers/object.js:247:5)                  
    at queryMethod (/home/argon/workspace/serverless-s3-local/node_modules/s3rver/lib/routes.js:32:5)                       
    at bucketExists (/home/argon/workspace/serverless-s3-local/node_modules/s3rver/lib/controllers/bucket.js:29:13)                 
    at queryMethod (/home/argon/workspace/serverless-s3-local/node_modules/s3rver/lib/routes.js:32:5)                          
    at /home/argon/workspace/serverless-s3-local/node_modules/s3rver/lib/s3rver.js:51:9
    at logger (/home/argon/workspace/serverless-s3-local/node_modules/koa-logger/index.js:67:7)
info: PUT /local-bucket/locale.json 200 224ms 0b                                                                     
```
                         
In my opinion, I think that the version of s3rver differs between my environment and yours.
Do you use the latest version serverless-s3-local ? If you don’t use it, please update your serverless-s3-local and try again ?

**Comment by gevorggalstyan** [comment]
Hi @ar90n 
Thank you for a quick reply. Unfortunately, all of the npm packages are the latest on the project.
Let me give you a bit more details for better insight:
node 10.16.0 (the latest stable version)
npm 6.10.2
"serverless": "^1.50.0",
"serverless-offline": "^5.10.1",
"serverless-s3-local": "^0.5.0",
"serverless-webpack": "^5.3.1",
"typescript": "^3.5.3",

So as you can see we are writing our code in typescript and using webpack to transpile it.

Here is the typescript code that crashes:
```typescript
import { Handler } from "aws-lambda";

export const ts: Handler = async () => {
  throw new Error("Something went wrong");
};
```

And here is the serverless config for that function
```yml
  partners-s3-listener:
    handler: src/functions/event-listeners/partners-s3-listener.ts
    timeout: 10
    events:
      - s3:
          bucket: partners-data
          event: "s3:ObjectCreated:*"
          existing: true
```

I have checked "Uncaught Exceptions" in VS Code to catch whatever might cause the crash, and here are the results:

```txt
Exception has occurred: Error
Error: Something went wrong
    at ./src/functions/event-listeners/partners-s3-listener.ts.exports.ts (/Users/g/Sites/app/.webpack/service/src/functions/event-listeners/webpack:/src/functions/event-listeners/partners-s3-listener.ts:17:9)
    at Object.func (/Users/g/Sites/app/node_modules/serverless-s3-local/index.js:385:11)
    at /Users/g/Sites/app/node_modules/serverless-s3-local/index.js:172:43
    at SafeSubscriber.s3eventSubscription.s3Event.pipe.subscribe.handler [as _next] (/Users/g/Sites/app/node_modules/serverless-s3-local/index.js:177:9)
    at SafeSubscriber.__tryOrUnsub (/Users/g/Sites/app/node_modules/rxjs/src/internal/Subscriber.ts:265:10)
    at SafeSubscriber.next (/Users/g/Sites/app/node_modules/rxjs/src/internal/Subscriber.ts:207:14)
    at Subscriber._next (/Users/g/Sites/app/node_modules/rxjs/src/internal/Subscriber.ts:139:22)
    at Subscriber.next (/Users/g/Sites/app/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at MergeMapSubscriber.notifyNext (/Users/g/Sites/app/node_modules/rxjs/src/internal/operators/mergeMap.ts:162:22)
    at InnerSubscriber._next (/Users/g/Sites/app/node_modules/rxjs/src/internal/InnerSubscriber.ts:17:17)
    at InnerSubscriber.Subscriber.next (/Users/g/Sites/app/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at /Users/g/Sites/app/node_modules/rxjs/src/internal/util/subscribeToArray.ts:9:16
    at Object.subscribeToResult (/Users/g/Sites/app/node_modules/rxjs/src/internal/util/subscribeToResult.ts:28:29)
    at MergeMapSubscriber._innerSub (/Users/g/Sites/app/node_modules/rxjs/src/internal/operators/mergeMap.ts:148:5)
    at MergeMapSubscriber._tryNext (/Users/g/Sites/app/node_modules/rxjs/src/internal/operators/mergeMap.ts:141:10)
    at MergeMapSubscriber._next (/Users/g/Sites/app/node_modules/rxjs/src/internal/operators/mergeMap.ts:125:12)
    at MergeMapSubscriber.Subscriber.next (/Users/g/Sites/app/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at MapSubscriber._next (/Users/g/Sites/app/node_modules/rxjs/src/internal/operators/map.ts:89:22)
    at MapSubscriber.Subscriber.next (/Users/g/Sites/app/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at S3rver.handler (/Users/g/Sites/app/node_modules/rxjs/src/internal/observable/fromEvent.ts:201:20)
    at S3rver.emit (events.js:198:13)
    at S3rver.EventEmitter.emit (domain.js:448:20)
    at triggerS3Event (/Users/g/Sites/app/node_modules/s3rver/lib/controllers/object.js:35:11)
    at Object.putObject (/Users/g/Sites/app/node_modules/s3rver/lib/controllers/object.js:280:5)
```

This is happening on line 38 of node_modules/serverless/bin/serverless.js, in this function:
```js
process.on('unhandledRejection', error => {
  if (process.listenerCount('unhandledRejection') > 1) {
    // User attached its own unhandledRejection handler, abort
    return;
  }
  throw error;
});
```

So as you may notice there is some unhandled rejection that does not have a handler, and that is why serverless crashes.

If I do basically the same with for example an SNS handler, the serverless does not crash as it actually finds a handler.

Please let me know if I can provide more info. Thank you.

**Comment by ar90n** [comment]
@gevorggalstyan 
Sorry for my late reply. I tried to reproduce your issue. But I couldn’t. If you don’t mind, could you share the minimum project that reproduce your issue?

**Comment by gevorggalstyan** [comment]
@ar90n 
We have a pretty complex app, not sure how of it you will need to repro the issue. Would you like to jump on a debugging session to take a look together?

**Comment by mungojam** [comment]
@gevorggalstyan what was the cause in the end? We are seeing similar but I haven't dug into it in any depth yet

**Comment by gevorggalstyan** [comment]
@mungojam I am not sure but I think this got resolved with the update of serverless-offline. I am really sorry to not give a better answer, this was so long ago.
